In [1]:
import numpy as np
import pandas as pd

In [2]:
np.nan

nan

In [3]:
pd.NA

In [4]:
pd.NaT

NaT

In [5]:
np.nan == np.nan

False

In [6]:
np.nan is np.nan

True

In [7]:
myvar = np.nan

In [8]:
myvar is np.nan

True

In [9]:
df = pd.read_csv('../../Python for ML/03-Pandas/movie_scores.csv')

In [10]:
df.head()

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [11]:
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [12]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [13]:
df['pre_movie_score'].notnull()

0     True
1    False
2    False
3     True
4     True
Name: pre_movie_score, dtype: bool

In [14]:
df[df['pre_movie_score'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [15]:
df[df['pre_movie_score'].isnull()]

  first_name last_name   age  sex  pre_movie_score  post_movie_score
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN

In [16]:
df[(df['pre_movie_score'].isnull()) & df['first_name'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [17]:
# Keept the data
# Drop the data
# Replace the data

In [18]:
#keep the data
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [22]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(*, axis: 'Axis' = 0, how: 'AnyAll | lib.NoDefault' = <no_default>, thresh: 'int | lib.NoDefault' = <no_default>, subset: 'IndexLabel | None' = None, inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [23]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [24]:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [26]:
help(df.agg)

Help on method aggregate in module pandas.core.frame:

aggregate(func=None, axis: 'Axis' = 0, *args, **kwargs) method of pandas.core.frame.DataFrame instance
    Aggregate using one or more operations over the specified axis.

    Parameters
    ----------
    func : function, str, list or dict
        Function to use for aggregating the data. If a function, must either
        work when passed a DataFrame or when passed to DataFrame.apply.

        Accepted combinations are:

        - function
        - string function name
        - list of functions and/or function names, e.g. ``[np.sum, 'mean']``
        - dict of axis labels -> functions, function names or list of such.
    axis : {0 or 'index', 1 or 'columns'}, default 0
            If 0 or 'index': apply function to each column.
            If 1 or 'columns': apply function to each row.
    *args
        Positional arguments to pass to `func`.
    **kwargs
        Keyword arguments to pass to `func`.

    Returns
    -------
    scalar, Series or DataFrame

        The return can be:

        * scalar : when Series.agg is called with single function
        * Series : when DataFrame.agg is called with a single function
        * DataFrame : when DataFrame.agg is called with several functions

    See Also
    --------
    DataFrame.apply : Perform any type of operations.
    DataFrame.transform : Perform transformation type operations.
    pandas.DataFrame.groupby : Perform operations over groups.
    pandas.DataFrame.resample : Perform operations over resampled bins.
    pandas.DataFrame.rolling : Perform operations over rolling window.
    pandas.DataFrame.expanding : Perform operations over expanding window.
    pandas.core.window.ewm.ExponentialMovingWindow : Perform operation over exponential
        weighted window.

    Notes
    -----
    The aggregation operations are always performed over an axis, either the
    index (default) or the column axis. This behavior is different from
    `numpy` aggregation functions (`mean`, `median`, `prod`, `sum`, `std`,
    `var`), where the default is to compute the aggregation of the flattened
    array, e.g., ``numpy.mean(arr_2d)`` as opposed to
    ``numpy.mean(arr_2d, axis=0)``.

    `agg` is an alias for `aggregate`. Use the alias.

    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    A passed user-defined-function will be passed a Series for evaluation.

    Examples
    --------
    >>> df = pd.DataFrame([[1, 2, 3],
    ...                    [4, 5, 6],
    ...                    [7, 8, 9],
    ...                    [np.nan, np.nan, np.nan]],
    ...                   columns=['A', 'B', 'C'])

    Aggregate these functions over the rows.

    >>> df.agg(['sum', 'min'])
            A     B     C
    sum  12.0  15.0  18.0
    min   1.0   2.0   3.0

    Different aggregations per column.

    >>> df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})
            A    B
    sum  12.0  NaN
    min   1.0  2.0
    max   NaN  8.0

    Aggregate different functions over the columns and rename the index of the resulting
    DataFrame.

    >>> df.agg(x=('A', 'max'), y=('B', 'min'), z=('C', 'mean'))
         A    B    C
    x  7.0  NaN  NaN
    y  NaN  2.0  NaN
    z  NaN  NaN  6.0

    Aggregate over the columns.

    >>> df.agg("mean", axis="columns")
    0    2.0
    1    5.0
    2    8.0
    3    NaN
    dtype: float64

In [27]:
help(df.index)

Help on RangeIndex in module pandas.core.indexes.range object:

class RangeIndex(pandas.core.indexes.base.Index)
 |  RangeIndex(start=None, stop=None, step=None, dtype: 'Dtype | None' = None, copy: 'bool' = False, name: 'Hashable | None' = None) -> 'Self'
 |
 |  Immutable Index implementing a monotonic integer range.
 |
 |  RangeIndex is a memory-saving special case of an Index limited to representing
 |  monotonic ranges with a 64-bit dtype. Using RangeIndex may in some instances
 |  improve computing speed.
 |
 |  This is the default index type used
 |  by DataFrame and Series when no explicit index is provided by the user.
 |
 |  Parameters
 |  ----------
 |  start : int (default: 0), range, or other RangeIndex instance
 |      If int and "stop" is not given, interpreted as "stop" instead.
 |  stop : int (default: 0)
 |  step : int (default: 1)
 |  dtype : np.int64
 |      Unused, accepted for homogeneity with other index types.
 |  copy : bool, default False
 |      Unused, accepted for homogeneity with other index types.
 |  name : object, optional
 |      Name to be stored in the index.
 |
 |  Attributes
 |  ----------
 |  start
 |  stop
 |  step
 |
 |  Methods
 |  -------
 |  from_range
 |
 |  See Also
 |  --------
 |  Index : The base pandas Index type.
 |
 |  Examples
 |  --------
 |  >>> list(pd.RangeIndex(5))
 |  [0, 1, 2, 3, 4]
 |
 |  >>> list(pd.RangeIndex(-2, 4))
 |  [-2, -1, 0, 1, 2, 3]
 |
 |  >>> list(pd.RangeIndex(0, 10, 2))
 |  [0, 2, 4, 6, 8]
 |
 |  >>> list(pd.RangeIndex(2, -10, -3))
 |  [2, -1, -4, -7]
 |
 |  >>> list(pd.RangeIndex(0))
 |  []
 |
 |  >>> list(pd.RangeIndex(1, 0))
 |  []
 |
 |  Method resolution order:
 |      RangeIndex
 |      pandas.core.indexes.base.Index
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.arraylike.OpsMixin
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __contains__(self, key: 'Any') -> 'bool'
 |      Return a boolean indicating whether the provided key is in the index.
 |
 |      Parameters
 |      ----------
 |      key : label
 |          The key to check if it is present in the index.
 |
 |      Returns
 |      -------
 |      bool
 |          Whether the key search is in the index.
 |
 |      Raises
 |      ------
 |      TypeError
 |          If the key is not hashable.
 |
 |      See Also
 |      --------
 |      Index.isin : Returns an ndarray of boolean dtype indicating whether the
 |          list-like key is in the index.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index([1, 2, 3, 4])
 |      >>> idx
 |      Index([1, 2, 3, 4], dtype='int64')
 |
 |      >>> 2 in idx
 |      True
 |      >>> 6 in idx
 |      False
 |
 |  __floordiv__(self, other)
 |
 |  __getitem__(self, key)
 |      Conserve RangeIndex type for scalar and slice keys.
 |
 |  __iter__(self) -> 'Iterator[int]'
 |      Return an iterator of the values.
 |
 |      These are each a scalar type, which is a Python scalar
 |      (for str, int, float) or a pandas scalar
 |      (for Timestamp/Timedelta/Interval/Period)
 |
 |      Returns
 |      -------
 |      iterator
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series([1, 2, 3])
 |      >>> for x in s:
 |      ...     print(x)
 |      1
 |      2
 |      3
 |
 |  __len__(self) -> 'int'
 |      return the length of the RangeIndex
 |
 |  __reduce__(self)
 |      Helper for pickle.
 |
 |  all(self, *args, **kwargs) -> 'bool'
 |      Return whether all elements are Truthy.
 |
 |      Parameters
 |      ----------
 |      *args
 |          Required for compatibility with numpy.
 |      **kwargs
 |          Required for compatibility with numpy.
 |
 |      Returns
 |      -------
 |      bool or array-like (if axis is specified)
 |          A single element array-like may be converted to bool.
 |
 |      See Also
 |      --------
 |      Index.any : Return whether any element in an Index is True.
 |      Series.any : Return whether any element in a Series is True.
 |      Series.all : Return whether all elements in a Series are True.
 |
 |      Notes
 |      -----
 |      Not a Number (NaN), positive infinity and negative infinity
 |      evaluate to True because these are not equal to zero.
 |
 |      Examples
 |      --------
 |      True, because nonzero integers are considered True.
 |
 |      >>> pd.Index([1, 2, 3]).all()
 |      True
 |
 |      False, because ``0`` is considered False.
 |
 |      >>> pd.Index([0, 1, 2]).all()
 |      False
 |
 |  any(self, *args, **kwargs) -> 'bool'
 |      Return whether any element is Truthy.
 |
 |      Parameters
 |      ----------
 |      *args
 |          Required for compatibility with numpy.
 |      **kwargs
 |          Required for compatibility with numpy.
 |
 |      Returns
 |      -------
 |      bool or array-like (if axis is specified)
 |          A single element array-like may be converted to bool.
 |
 |      See Also
 |      --------
 |      Index.all : Return whether all elements are True.
 |      Series.all : Return whether all elements are True.
 |
 |      Notes
 |      -----
 |      Not a Number (NaN), positive infinity and negative infinity
 |      evaluate to True because these are not equal to zero.
 |
 |      Examples
 |      --------
 |      >>> index = pd.Index([0, 1, 2])
 |      >>> index.any()
 |      True
 |
 |      >>> index = pd.Index([0, 0, 0])
 |      >>> index.any()
 |      False
 |
 |  argsort(self, *args, **kwargs) -> 'npt.NDArray[np.intp]'
 |      Returns the indices that would sort the index and its
 |      underlying data.
 |
 |      Returns
 |      -------
 |      np.ndarray[np.intp]
 |
 |      See Also
 |      --------
 |      numpy.ndarray.argsort
 |
 |  copy(self, name: 'Hashable | None' = None, deep: 'bool' = False) -> 'Self'
 |      Make a copy of this object.
 |
 |      Name is set on the new object.
 |
 |      Parameters
 |      ----------
 |      name : Label, optional
 |          Set name for new object.
 |      deep : bool, default False
 |
 |      Returns
 |      -------
 |      Index
 |          Index refer to new object which is a copy of this object.
 |
 |      Notes
 |      -----
 |      In most cases, there should be no functional difference from using
 |      ``deep``, but if ``deep`` is passed it will attempt to deepcopy.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['a', 'b', 'c'])
 |      >>> new_idx = idx.copy()
 |      >>> idx is new_idx
 |      False
 |
 |  delete(self, loc) -> 'Index'
 |      Make new Index with passed location(-s) deleted.
 |
 |      Parameters
 |      ----------
 |      loc : int or list of int
 |          Location of item(-s) which will be deleted.
 |          Use a list of locations to delete more than one value at the same time.
 |
 |      Returns
 |      -------
 |      Index
 |          Will be same type as self, except for RangeIndex.
 |
 |      See Also
 |      --------
 |      numpy.delete : Delete any rows and column from NumPy array (ndarray).
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['a', 'b', 'c'])
 |      >>> idx.delete(1)
 |      Index(['a', 'c'], dtype='object')
 |
 |      >>> idx = pd.Index(['a', 'b', 'c'])
 |      >>> idx.delete([0, 2])
 |      Index(['b'], dtype='object')
 |
 |  equals(self, other: 'object') -> 'bool'
 |      Determines if two Index objects contain the same elements.
 |
 |  factorize(self, sort: 'bool' = False, use_na_sentinel: 'bool' = True) -> 'tuple[npt.NDArray[np.intp], RangeIndex]'
 |      Encode the object as an enumerated type or categorical variable.
 |
 |      This method is useful for obtaining a numeric representation of an
 |      array when all that matters is identifying distinct values. `factorize`
 |      is available as both a top-level function :func:`pandas.factorize`,
 |      and as a method :meth:`Series.factorize` and :meth:`Index.factorize`.
 |
 |      Parameters
 |      ----------
 |      sort : bool, default False
 |          Sort `uniques` and shuffle `codes` to maintain the
 |          relationship.
 |
 |      use_na_sentinel : bool, default True
 |          If True, the sentinel -1 will be used for NaN values. If False,
 |          NaN values will be encoded as non-negative integers and will not drop the
 |          NaN from the uniques of the values.
 |
 |          .. versionadded:: 1.5.0
 |
 |      Returns
 |      -------
 |      codes : ndarray
 |          An integer ndarray that's an indexer into `uniques`.
 |          ``uniques.take(codes)`` will have the same values as `values`.
 |      uniques : ndarray, Index, or Categorical
 |          The unique valid values. When `values` is Categorical, `uniques`
 |          is a Categorical. When `values` is some other pandas object, an
 |          `Index` is returned. Otherwise, a 1-D ndarray is returned.
 |
 |          .. note::
 |
 |             Even if there's a missing value in `values`, `uniques` will
 |             *not* contain an entry for it.
 |
 |      See Also
 |      --------
 |      cut : Discretize continuous-valued array.
 |      unique : Find the unique value in an array.
 |
 |      Notes
 |      -----
 |      Reference :ref:`the user guide <reshaping.factorize>` for more examples.
 |
 |      Examples
 |      --------
 |      These examples all show factorize as a top-level method like
 |      ``pd.factorize(values)``. The results are identical for methods like
 |      :meth:`Series.factorize`.
 |
 |      >>> codes, uniques = pd.factorize(np.array(['b', 'b', 'a', 'c', 'b'], dtype="O"))
 |      >>> codes
 |      array([0, 0, 1, 2, 0])
 |      >>> uniques
 |      array(['b', 'a', 'c'], dtype=object)
 |
 |      With ``sort=True``, the `uniques` will be sorted, and `codes` will be
 |      shuffled so that the relationship is the maintained.
 |
 |      >>> codes, uniques = pd.factorize(np.array(['b', 'b', 'a', 'c', 'b'], dtype="O"),
 |      ...                               sort=True)
 |      >>> codes
 |      array([1, 1, 0, 2, 1])
 |      >>> uniques
 |      array(['a', 'b', 'c'], dtype=object)
 |
 |      When ``use_na_sentinel=True`` (the default), missing values are indicated in
 |      the `codes` with the sentinel value ``-1`` and missing values are not
 |      included in `uniques`.
 |
 |      >>> codes, uniques = pd.factorize(np.array(['b', None, 'a', 'c', 'b'], dtype="O"))
 |      >>> codes
 |      array([ 0, -1,  1,  2,  0])
 |      >>> uniques
 |      array(['b', 'a', 'c'], dtype=object)
 |
 |      Thus far, we've only factorized lists (which are internally coerced to
 |      NumPy arrays). When factorizing pandas objects, the type of `uniques`
 |      will differ. For Categoricals, a `Categorical` is returned.
 |
 |      >>> cat = pd.Categorical(['a', 'a', 'c'], categories=['a', 'b', 'c'])
 |      >>> codes, uniques = pd.factorize(cat)
 |      >>> codes
 |      array([0, 0, 1])
 |      >>> uniques
 |      ['a', 'c']
 |      Categories (3, object): ['a', 'b', 'c']
 |
 |      Notice that ``'b'`` is in ``uniques.categories``, despite not being
 |      present in ``cat.values``.
 |
 |      For all other pandas objects, an Index of the appropriate type is
 |      returned.
 |
 |      >>> cat = pd.Series(['a', 'a', 'c'])
 |      >>> codes, uniques = pd.factorize(cat)
 |      >>> codes
 |      array([0, 0, 1])
 |      >>> uniques
 |      Index(['a', 'c'], dtype='object')
 |
 |      If NaN is in the values, and we want to include NaN in the uniques of the
 |      values, it can be achieved by setting ``use_na_sentinel=False``.
 |
 |      >>> values = np.array([1, 2, 1, np.nan])
 |      >>> codes, uniques = pd.factorize(values)  # default: use_na_sentinel=True
 |      >>> codes
 |      array([ 0,  1,  0, -1])
 |      >>> uniques
 |      array([1., 2.])
 |
 |      >>> codes, uniques = pd.factorize(values, use_na_sentinel=False)
 |      >>> codes
 |      array([0, 1, 0, 2])
 |      >>> uniques
 |      array([ 1.,  2., nan])
 |
 |  get_loc(self, key) -> 'int'
 |      Get integer location, slice or boolean mask for requested label.
 |
 |      Parameters
 |      ----------
 |      key : label
 |
 |      Returns
 |      -------
 |      int if unique index, slice if monotonic index, else mask
 |
 |      Examples
 |      --------
 |      >>> unique_index = pd.Index(list('abc'))
 |      >>> unique_index.get_loc('b')
 |      1
 |
 |      >>> monotonic_index = pd.Index(list('abbc'))
 |      >>> monotonic_index.get_loc('b')
 |      slice(1, 3, None)
 |
 |      >>> non_monotonic_index = pd.Index(list('abcb'))
 |      >>> non_monotonic_index.get_loc('b')
 |      array([False,  True, False,  True])
 |
 |  insert(self, loc: 'int', item) -> 'Index'
 |      Make new Index inserting new item at location.
 |
 |      Follows Python numpy.insert semantics for negative values.
 |
 |      Parameters
 |      ----------
 |      loc : int
 |      item : object
 |
 |      Returns
 |      -------
 |      Index
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['a', 'b', 'c'])
 |      >>> idx.insert(1, 'x')
 |      Index(['a', 'x', 'b', 'c'], dtype='object')
 |
 |  max(self, axis=None, skipna: 'bool' = True, *args, **kwargs) -> 'int'
 |      The maximum value of the RangeIndex
 |
 |  memory_usage(self, deep: 'bool' = False) -> 'int'
 |      Memory usage of my values
 |
 |      Parameters
 |      ----------
 |      deep : bool
 |          Introspect the data deeply, interrogate
 |          `object` dtypes for system-level memory consumption
 |
 |      Returns
 |      -------
 |      bytes used
 |
 |      Notes
 |      -----
 |      Memory usage does not include memory consumed by elements that
 |      are not components of the array if deep=False
 |
 |      See Also
 |      --------
 |      numpy.ndarray.nbytes
 |
 |  min(self, axis=None, skipna: 'bool' = True, *args, **kwargs) -> 'int'
 |      The minimum value of the RangeIndex
 |
 |  sort_values(self, *, return_indexer: 'bool' = False, ascending: 'bool' = True, na_position: 'NaPosition' = 'last', key: 'Callable | None' = None) -> 'Self | tuple[Self, np.ndarray | RangeIndex]'
 |      Return a sorted copy of the index.
 |
 |      Return a sorted copy of the index, and optionally return the indices
 |      that sorted the index itself.
 |
 |      Parameters
 |      ----------
 |      return_indexer : bool, default False
 |          Should the indices that would sort the index be returned.
 |      ascending : bool, default True
 |          Should the index values be sorted in an ascending order.
 |      na_position : {'first' or 'last'}, default 'last'
 |          Argument 'first' puts NaNs at the beginning, 'last' puts NaNs at
 |          the end.
 |      key : callable, optional
 |          If not None, apply the key function to the index values
 |          before sorting. This is similar to the `key` argument in the
 |          builtin :meth:`sorted` function, with the notable difference that
 |          this `key` function should be *vectorized*. It should expect an
 |          ``Index`` and return an ``Index`` of the same shape.
 |
 |      Returns
 |      -------
 |      sorted_index : pandas.Index
 |          Sorted copy of the index.
 |      indexer : numpy.ndarray, optional
 |          The indices that the index itself was sorted by.
 |
 |      See Also
 |      --------
 |      Series.sort_values : Sort values of a Series.
 |      DataFrame.sort_values : Sort values in a DataFrame.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index([10, 100, 1, 1000])
 |      >>> idx
 |      Index([10, 100, 1, 1000], dtype='int64')
 |
 |      Sort values in ascending order (default behavior).
 |
 |      >>> idx.sort_values()
 |      Index([1, 10, 100, 1000], dtype='int64')
 |
 |      Sort values in descending order, and also get the indices `idx` was
 |      sorted by.
 |
 |      >>> idx.sort_values(ascending=False, return_indexer=True)
 |      (Index([1000, 100, 10, 1], dtype='int64'), array([3, 1, 0, 2]))
 |
 |  symmetric_difference(self, other, result_name: 'Hashable | None' = None, sort=None)
 |      Compute the symmetric difference of two Index objects.
 |
 |      Parameters
 |      ----------
 |      other : Index or array-like
 |      result_name : str
 |      sort : bool or None, default None
 |          Whether to sort the resulting index. By default, the
 |          values are attempted to be sorted, but any TypeError from
 |          incomparable elements is caught by pandas.
 |
 |          * None : Attempt to sort the result, but catch any TypeErrors
 |            from comparing incomparable elements.
 |          * False : Do not sort the result.
 |          * True : Sort the result (which may raise TypeError).
 |
 |      Returns
 |      -------
 |      Index
 |
 |      Notes
 |      -----
 |      ``symmetric_difference`` contains elements that appear in either
 |      ``idx1`` or ``idx2`` but not both. Equivalent to the Index created by
 |      ``idx1.difference(idx2) | idx2.difference(idx1)`` with duplicates
 |      dropped.
 |
 |      Examples
 |      --------
 |      >>> idx1 = pd.Index([1, 2, 3, 4])
 |      >>> idx2 = pd.Index([2, 3, 4, 5])
 |      >>> idx1.symmetric_difference(idx2)
 |      Index([1, 5], dtype='int64')
 |
 |  take(self, indices, axis: 'Axis' = 0, allow_fill: 'bool' = True, fill_value=None, **kwargs) -> 'Index'
 |      Return a new Index of the values selected by the indices.
 |
 |      For internal compatibility with numpy arrays.
 |
 |      Parameters
 |      ----------
 |      indices : array-like
 |          Indices to be taken.
 |      axis : int, optional
 |          The axis over which to select values, always 0.
 |      allow_fill : bool, default True
 |      fill_value : scalar, default None
 |          If allow_fill=True and fill_value is not None, indices specified by
 |          -1 are regarded as NA. If Index doesn't hold NA, raise ValueError.
 |
 |      Returns
 |      -------
 |      Index
 |          An index formed of elements at the given indices. Will be the same
 |          type as self, except for RangeIndex.
 |
 |      See Also
 |      --------
 |      numpy.ndarray.take: Return an array formed from the
 |          elements of a at the given indices.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['a', 'b', 'c'])
 |      >>> idx.take([2, 2, 1, 2])
 |      Index(['c', 'c', 'b', 'c'], dtype='object')
 |
 |  tolist(self) -> 'list[int]'
 |      Return a list of the values.
 |
 |      These are each a scalar type, which is a Python scalar
 |      (for str, int, float) or a pandas scalar
 |      (for Timestamp/Timedelta/Interval/Period)
 |
 |      Returns
 |      -------
 |      list
 |
 |      See Also
 |      --------
 |      numpy.ndarray.tolist : Return the array as an a.ndim-levels deep
 |          nested list of Python scalars.
 |
 |      Examples
 |      --------
 |      For Series
 |
 |      >>> s = pd.Series([1, 2, 3])
 |      >>> s.to_list()
 |      [1, 2, 3]
 |
 |      For Index:
 |
 |      >>> idx = pd.Index([1, 2, 3])
 |      >>> idx
 |      Index([1, 2, 3], dtype='int64')
 |
 |      >>> idx.to_list()
 |      [1, 2, 3]
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_range(data: 'range', name=None, dtype: 'Dtype | None' = None) -> 'Self'
 |      Create :class:`pandas.RangeIndex` from a ``range`` object.
 |
 |      Returns
 |      -------
 |      RangeIndex
 |
 |      Examples
 |      --------
 |      >>> pd.RangeIndex.from_range(range(5))
 |      RangeIndex(start=0, stop=5, step=1)
 |
 |      >>> pd.RangeIndex.from_range(range(2, -10, -3))
 |      RangeIndex(start=2, stop=-10, step=-3)
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(cls, start=None, stop=None, step=None, dtype: 'Dtype | None' = None, copy: 'bool' = False, name: 'Hashable | None' = None) -> 'Self'
 |      Create and return a new object.  See help(type) for accurate signature.
 |

In [28]:
df.dropna(thresh=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [29]:
df.dropna(thresh=4)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [30]:
df.dropna(thresh=5)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [31]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [32]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [34]:
df.dropna(subset=['last_name'])

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [35]:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [36]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [37]:
df.fillna('VALUE!')

  first_name last_name     age     sex pre_movie_score post_movie_score
0        Tom     Hanks    63.0       m             8.0             10.0
1     VALUE!    VALUE!  VALUE!  VALUE!          VALUE!           VALUE!
2       Hugh   Jackman    51.0       m          VALUE!           VALUE!
3      Oprah   Winfrey    66.0       f             6.0              8.0
4       Emma     Stone    31.0       f             7.0              9.0

In [38]:
df['pre_movie_score'].fillna(0)

0    8.0
1    0.0
2    0.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [39]:
df['pre_movie_score'].mean()

np.float64(7.0)

In [40]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [41]:
airline_tix = {'first':100,'business':np.nan,'economy-plus':50,'economy':30}

In [42]:
ser = pd.Series(airline_tix)

In [43]:
ser

first           100.0
business          NaN
economy-plus     50.0
economy          30.0
dtype: float64

In [44]:
ser.interpolate()

first           100.0
business         75.0
economy-plus     50.0
economy          30.0
dtype: float64